language: rust

sudo: false
matrix:
  include:
    - os: linux
      rust: nightly
      env:
        - FORMAT=1
        - BENCH=1
      before_script:
        - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
        - rustup component add rustfmt-preview
      after_success:
        - travis-cargo doc-upload
    - os: linux
      rust: beta
    - os: linux
      rust: stable
    - os: osx
      rust: stable
script:
  - if [ "$FORMAT" = "1" ]; then cargo fmt -- --write-mode=diff; fi
  - cargo build
  - cargo test
  - rustdoc --test README.md -L target/debug -L target/debug/deps
  - cargo doc --no-deps
  - if [ "$BENCH" = "1" ]; then cargo bench; fi
env:
  global:
    - secure: joY4pRiqQITVhRYo+NU5qVSgE0XceKgz1/LZZ5KK2c2137KzRHy58DJXg28meYbC4TqN41Ykvm7voNKlMGrWCmPY1wOELd+tQwZV/heNVHZD2oGA+y75XEjUFK8pBE1IXOU4QAsFLBnWz08zx1qY5bYY2D8WrdmSSekTZ1AoymaMvXDIEZRy7KQrmvPZIPNOJ0baG+2W+BCnvDstezqbXE9MN5l3OirhhS0eH1xSIfUotOytw8NtIbrYeE9I6/j3DtOPXuoDOLBTikaeK4YnxM57yZp+bZ+xAaDQ1oUUI7NKacjCdMV/rQnKtTnHQW+weehYSyICrDzKJZA1yUjP16mk6k/N/hkExu8xbkyRtNFqoW6uJ7O0r92CuadLincUOYxCl+5vNwOCb6sm/MenOtb2LpyC4OwkAAqECVR7LEh9AH5JekifuIyqB4wIz51yrxTKY/CBBckYGe8+m+K7iOZ+l67APJx/tD/cxPRElRc0v++1ceQ1hGGPsBRD91a+ke/Qqw50QTHGQAtIseX20NOFxNi86FIR6zm+QWZ4NhvC2xOO+KsQMNJThTItxFopSXEoe4tk9rEQUwjNRKWR7uIXwYjm9wOa2R1zbbRImdlZNmBhfpBPY2U3btICs4rJWaPQ53KdDt87f7MiPjLPQdZGxnt/C+q808lzNdn2X88=

notifications:
  email:
    on_success: never
